SELECT PRODUCT.MAKER, AVG(LAPTOP.PRICE) as average_laptop_price
FROM LAPTOP
INNER JOIN PRODUCT
ON LAPTOP.MODEL = PRODUCT.MODEL
WHERE PRODUCT.MAKER = "B"

UNION ALL

SELECT PRODUCT.MAKER, AVG(PC.PRICE) as average_pc_price
FROM PC
INNER JOIN PRODUCT
ON PC.MODEL = PRODUCT.MODEL
WHERE PRODUCT.MAKER = "B";