SELECT AVG(HD) as avg_hd
FROM PC
INNER JOIN PRODUCT
ON PC.MODEL = PRODUCT.MODEL
WHERE PRODUCT.MAKER IN 
    (SELECT DISTINCT MAKER
    FROM PRODUCT
    WHERE TYPE = "Printer"

    INTERSECT

    SELECT DISTINCT MAKER
    FROM PRODUCT
    WHERE TYPE = "PC");

