-- SELECT SHIPS.NAME, CLASSES.COUNTRY, CLASSES.NUMGUNS, SHIPS.LAUNCHED
-- FROM SHIPS
-- INNER JOIN CLASSES
-- ON SHIPS.CLASS = CLASSES.CLASS
-- WHERE SHIPS.NAME IN 

-- ;
SELECT NAME
FROM SHIPS
INNER JOIN CLASSES
ON SHIPS.CLASS = CLASSES.CLASS
WHERE SHIPS.CLASS IN 
    (SELECT CLASSES.CLASS
    FROM CLASSES 
    LEFT JOIN SHIPS
    ON CLASSES.CLASS = SHIPS.CLASS
    WHERE SHIPS.CLASS IS NULL);